.TH man 1 "June 2023" "0.0.1" "srcMetrics"
.SH NAME
srcMetrics \- Calculates static metrics from C source code, srcML, or srcGraph files
.SH SYNOPSIS
srcmetrics [options] <src_infile>... [-o <srcMetrics_outfile>]
srcmetrics [options] <srcML_infile>... [-o <srcMetrics_outfile>]
srcmetrics [options] <srcGraph_infile>... [-o <srcMetrics_outfile>]
.SH DESCRIPTION
.SH OPTIONS
GENERAL OPTIONS:
  -h,--help                  Output this help message and exit
  -V,--version               Output version number and exit
  -v,--verbose               Status information to stderr
  -c,--copyright             Output the copyright message and exit
  -q,--quiet                 Suppress status messages
  -o,--output FILE           Write output to FILE
  -l,--language LANG         Set the source-code language to C
  --files-from FILE          Input source-code filenames from FILE instead of command-line arguments

SRCMETRICS:
  -m,--metric METRIC         Report this METRIC if possible, excludes all unspecified metrics
  -e,--exclude METRIC        Exclude this METRIC from the output

METADATA OPTIONS:
  -L,--list                  Output the list of supported metrics and exit
  -s,--show METRIC           Output detailed information on METRIC and exit
.SH SEE ALSO
srcml(1), dot(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Yavuz Koroglu
.SH COPYRIGHT
Copyright (C) 2023 srcML, LLC. (www.srcML.org)
